name: zruri
description: "A new Flutter project."
publish_to: "none"
version: 0.3.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.2
  firebase_crashlytics: ^4.3.9
  firebase_analytics: ^11.5.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  pinput: ^5.0.1
  country_picker: ^2.0.27
  flutter_svg: ^2.2.0
  animations: ^2.0.11
  cloud_firestore: ^5.6.11
  phone_numbers_parser: ^9.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flutter_spinkit: ^5.2.1
  get_storage: ^2.1.1
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_places_flutter: ^2.1.0
  geolocator: ^14.0.2
  google_geocoding_api: ^1.5.2
  animated_text_kit: ^4.2.3
  image_picker: ^1.1.2
  circular_profile_avatar: ^2.0.5
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9
  cupertino_icons: ^1.0.8
  share_plus: ^11.1.0
  app_links: ^6.4.1
  uni_links: ^0.5.1
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_email_sender: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
