// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IDIpRVFiOcdth8XL0ID-51vniZbLPP4',
    appId: '1:321467844839:android:91bb622214ce43e054fa42',
    messagingSenderId: '321467844839',
    projectId: 'zruri-app',
    storageBucket: 'zruri-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuD1HVI6OYwRbBcXy-BNsSu3dQUFYRZWs',
    appId: '1:321467844839:ios:0a6dd153b18c14cf54fa42',
    messagingSenderId: '321467844839',
    projectId: 'zruri-app',
    storageBucket: 'zruri-app.appspot.com',
    androidClientId: '321467844839-n8puoukg3l2qp0lej9qpk96qi7vfi7e3.apps.googleusercontent.com',
    iosClientId: '321467844839-oo377sulqraucl4uu4uevkb7667h0qh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.zruriFlutter',
  );
}
